apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: portfolio-app-development

# Base configuration to inherit from
bases:
  - ../../base

# Namespace for development
namespace: portfolio-dev

# Name suffix for development resources
nameSuffix: -dev

# Image tag for development
images:
  - name: portfolio-app
    newTag: dev-latest

# Patches for development-specific configurations
patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml

# ConfigMap generator for development-specific env vars
configMapGenerator:
  - name: portfolio-app-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DEBUG=true

# Common labels for development
commonLabels:
  environment: development
  tier: frontend
