apiVersion: apps/v1
kind: Deployment
metadata:
  name: iamsg97-personal-website
spec:
  template:
    spec:
      containers:
        - name: iamsg97-personal-website
          resources:
            requests:
              memory: '32Mi'
              cpu: '25m'
            limits:
              memory: '64Mi'
              cpu: '50m'
