apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: portfolio-app-production

# Base configuration to inherit from
bases:
  - ../../base

# Namespace for production
namespace: portfolio-prod

# Name suffix for production resources
nameSuffix: -prod

# Image tag for production (will be set by CI/CD)
images:
  - name: portfolio-app
    newTag: v1.0.2

# Patches for production-specific configurations
patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml

# Additional resources for production
resources:
  - hpa-patch.yaml

# ConfigMap generator for production-specific env vars
configMapGenerator:
  - name: portfolio-app-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=error
      - DEBUG=false

# Common labels for production
commonLabels:
  environment: production
  tier: frontend
