apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
spec:
  template:
    spec:
      containers:
      - name: portfolio-app
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
