apiVersion: apps/v1
kind: Deployment
metadata:
  name: iamsg97-personal-website
spec:
  template:
    spec:
      containers:
        - name: iamsg97-personal-website
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '200m'
