apiVersion: apps/v1
kind: Deployment
metadata:
  name: iamsg97-personal-website
  labels:
    app: iamsg97-personal-website
    component: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: iamsg97-personal-website
  template:
    metadata:
      labels:
        app: iamsg97-personal-website
        component: frontend
    spec:
      containers:
        - name: iamsg97-personal-website
          image: iamsg97-personal-website:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: NODE_ENV
              value: 'production'
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '128Mi'
              cpu: '100m'
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 101 # nginx user
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
