apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: portfolio-app-base

# Common labels applied to all resources
commonLabels:
  app: portfolio-app
  version: v1.0.2

# Common annotations
commonAnnotations:
  contact: 'ghoshalsuvadeep594@gmail.com'
  documentation: 'https://github.com/iamsg97/personal-website'

# Resources to include
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml

# Image configurations
images:
  - name: portfolio-app
    newTag: v1.0.2

# ConfigMap generator (optional - can be used instead of configmap.yaml)
# configMapGenerator:
# - name: portfolio-app-config
#   literals: example configs like env or application.properties (if applicable)
#   - NODE_ENV=production
#   - APP_NAME=Portfolio App
#   - LOG_LEVEL=info

# Name prefix for all resources
namePrefix: ''

# Name suffix for all resources
nameSuffix: ''
# Namespace to deploy resources
# namespace: portfolio
